[project]
name = "zotfile-doctor"
version = "0.1.0"
description = "Zotfile directory consistency checker"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["cyclopts>=3.1.5", "rich>=13.9.4"]

[tool.ruff]
preview = true
output-format = "concise"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["COM", "CPY", "Q"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
